src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Donor</fullName>
        <active>true</active>
        <description>Donor to Rare</description>
        <label>Donor</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Corporate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual - Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual - Major</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NGO/Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Past Trustee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trustees</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Referral_Date__c</fullName>
        <label>Referral Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lapsed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Contact for Rare</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Flipcause_Transactions__c.object
<CustomObject>
    <description>Flat table of all Flipcause transactions. To be used as a way to more seamlessly create records on related account, contact, opportunity, and payment objects</description>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Card_Brand__c</fullName>
        <label>Card Brand</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Donation_Amount__c</fullName>
        <label>Donation Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <label>Flipcause Transactions</label>
    <nameField>
        <label>Flipcause Transactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flipcause Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Gift_Allocated_to_Segment__c</fullName>
        <inlineHelpText>Choose segment this gift should be counted under for board report</inlineHelpText>
        <label>Gift Allocated to Segment</label>
        <picklist>
            <picklistValues>
                <fullName>Trustee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Major Donor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NGO/Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Revenue (ex. trip payment)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Expected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payments__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payments</label>
        <referenceTo>Old_Payments__c</referenceTo>
        <relationshipLabel>Financials</relationshipLabel>
        <relationshipName>Proposals</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Payments__c.object
<CustomObject>
    <description>Donation or grant payments</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Funding Record</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N300000026zTXEAY</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Amount__c</fullName>
        <label>Payment Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Date__c</fullName>
        <label>Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <picklist>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Amex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wire Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Kind</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PayPal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Pledge_Year__c</fullName>
        <inlineHelpText>This is the fiscal year (of the pledge schedule) that the payment should be counted in. May differ from the actual payment date.</inlineHelpText>
        <label>Pledge Year (FY)</label>
        <picklist>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2021</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2022</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2023</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2024</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2025</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>Payment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateOppsFromFlipcause.cls
/**
 * Created by jdove on 11/5/15.
 *
 * This class will take data inserted into the Flipcause_Transactions__c object and create Households, Persons,
 * Opportunities, and Payments.
 */

public with sharing class CreateOppsFromFlipcause {


//    TODO - Create a method that checks for existing donors using e-mail address

    public static void newOppsNewDonors(List<Flipcause_Transactions__c> newFlipcauseTransactions) {
        String currentFiscalYear = [SELECT FiscalYearSettings.Name FROM Period WHERE Type = 'Year'
                                    AND StartDate <= TODAY and EndDate >= TODAY].FiscalYearSettings.Name;

        for(Flipcause_Transactions__c newFlips : newFlipcauseTransactions) {

            Account household = new Account(
                    Name='The ' + newFlips.First_Name__c + ' ' + newFlips.Last_Name__c + ' Household'
            );
            insert household;

            Contact con = new Contact(
                    AccountId = household.Id,
                    FirstName = newFlips.First_Name__c,
                    LastName = newFlips.Last_Name__c,
                    RecordTypeId = '0123000000054Oz', // Hardcoding is bad!
                    Contact_Type__c = 'Individual - Member',
                    Status__c = 'Donor',
                    LeadSource = 'Web',
                    Referral_Date__c = newFlips.Transaction_Date__c,
                    Email = newFlips.Email__c,
                    MailingStreet = newFlips.Address__c,
                    MailingCity = newFlips.City__c,
                    MailingState = newFlips.State__c,
                    Phone = newFlips.Phone__c,
                    MailingPostalCode = newFlips.Postal_Code__c
            );
            insert con;

            Opportunity fund = new Opportunity(
                    AccountId = household.Id,
                    RecordTypeId = '012300000005TlN', // Hardcoding is bad!
                    Name = con.FirstName + ' ' + con.LastName + ' - Donation ' + newFlips.Transaction_Date__c,
                    CloseDate = newFlips.Transaction_Date__c,
                    Gift_Allocated_to_Segment__c = 'Individual',
                    Amount = newFlips.Donation_Amount__c,
                    Probability = 100,
                    StageName = 'Closed Won',
                    Comments__c = newFlips.Message__c
            );
            insert fund;

            OpportunityContactRole role = new OpportunityContactRole(
                    ContactId = con.Id,
                    OpportunityId = fund.Id,
                    Role = 'Donor'
            );
            insert role;

            Payments__c payment = new Payments__c(
                    RecordTypeId = '012300000005VFC', // Hardcoding is bad!
                    Opportunity__c = fund.Id,
                    Payment_Date__c = newFlips.Transaction_Date__c,
                    Payment_Amount__c = newFlips.Amount__c,
                    Pledge_Year__c = currentFiscalYear,
                    Payment_Status__c = 'Received',
                    Payment_Method__c = newFlips.Card_Brand__c
            );
            insert payment;

        }
    }

}