src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Cohort__c</fullName>
        <label>Cohort</label>
        <picklist>
            <picklistValues>
                <fullName>Bogor 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bogor 2 - Spring &apos;07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bogor 3 - Fall &apos;08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bogor 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bogor 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bogor 6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil Future</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China 1 - Summer &apos;08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China 3 Agriculture</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guad 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guad 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guad 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guad 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guad 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guad 6 - Fall &apos;07</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guad 7 - Fall &apos;08</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guad 8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guad 9</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guad 10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guad 11</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEP 1 - Spring &apos;09</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEP 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEP 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PEP 5 - Fish Forever</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phili 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phili 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WIO 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kent 1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Countries__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Cohorts__c</fullName>
        <label>Cohorts</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Countries</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Cohort__c</fullName>
        <formula>IF (LEN(Web_Cohort__c) &gt; 0, 
Case (Web_Cohort__c,
&quot;PEP&quot;, &quot;PEP Future&quot;,
&quot;China&quot;, &quot;China Future&quot;,
&quot;Guad&quot;, &quot;Guad Future&quot;,
&quot;Bogor&quot;, &quot;Bogor Future&quot;,
&quot;No Cohort Assigned&quot;
)
,
Case( text(Applying_for_Program_at__c) , 
&quot;Bogor Agricultural University, Indonesia (Bahasa Indonesia)&quot;, Case( text(Date_Seeking_Admission__c) , &quot;February 2010&quot;, &quot;Bogor 4&quot;,&quot;February 2011&quot;, &quot;Bogor 5&quot;,&quot;February 2012&quot;, &quot;Bogor 6&quot;,&quot;Lead Cohort Unknown&quot; ), 
&quot;University of Guadalajara, Mexico (Spanish)&quot;,Case( text(Date_Seeking_Admission__c) , &quot;February 2010&quot;, &quot;Guad 8&quot;,&quot;February 2011&quot;, &quot;Guad 9&quot;,&quot;February 2012&quot;, &quot;Guad 10&quot;,&quot;Lead Cohort Unknown&quot; ), 
&quot;Southwest Forestry University, China (Mandarin Chinese)&quot;,Case( text(Date_Seeking_Admission__c) , &quot;February 2010&quot;, &quot;China 2&quot;,&quot;February 2011&quot;, &quot;China 3&quot;,&quot;February 2012&quot;, &quot;China 4&quot;,&quot;Lead Cohort Unknown&quot; ), 
&quot;Georgetown University, USA (English)&quot;,Case( text(Date_Seeking_Admission__c) , &quot;February 2010&quot;, &quot;PEP 2&quot;,&quot;February 2011&quot;, &quot;PEP 3&quot;,&quot;February 2012&quot;, &quot;PEP 4&quot;,&quot;Lead Cohort Unknown&quot; ), 
&quot;Lead Cohort Unknown&quot; 
)
)</formula>
        <label>Cohort</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Countries__c</fullName>
        <inlineHelpText>In which countries is this Pride Lead interested in running Pride campaigns?</inlineHelpText>
        <label>Countries</label>
        <picklist>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brazil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>British Virgin Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brunei Darussalam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Burundi</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cambodia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cameroon</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cayman Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central African Republic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>China</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colombia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Congo</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cook Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Costa Rica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cote d&apos;Ivoire</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cyprus</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Projects__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Projects Interest (if applicable)</label>
        <referenceTo>Projects__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>R00N30000001B2hZEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>Lead Process</businessProcess>
        <description>Standard Lead - donors,orgs, etc</description>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/PADefaults__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To store defaults for PA form picklists</description>
    <fields>
        <fullName>Cohort__c</fullName>
        <label>Cohort</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Country_Error__c</fullName>
        <label>No Country Error</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Org_Type_Error_Msg__c</fullName>
        <label>No Org Type Error Msg</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Salutation_Error_Msg__c</fullName>
        <label>No Salutation Error Msg</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist_Values__c</fullName>
        <label>Picklist Values</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>PA Defaults</label>
</CustomObject>

src/objects/Projects__c.object
<CustomObject>
    <description>Conservation projects</description>
    <fields>
        <fullName>Cohort__c</fullName>
        <label>Cohort</label>
        <referenceTo>Cohort__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Dashboard_Id__c</fullName>
        <description>Used to generate Cohort specific dashboard data</description>
        <inlineHelpText>Do not use - admin only</inlineHelpText>
        <label>Dashboard Id</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Projects</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Dash_Table__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show in Dash Table?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <label>Display Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reference_Name__c</fullName>
        <description>To enable easy lookup against stage names, we can store the related lead/application stage in this field</description>
        <label>Reference Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Tracking</label>
    <nameField>
        <label>Stage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tracking_Details__c.object
<CustomObject>
    <fields>
        <fullName>Entry_Date__c</fullName>
        <label>Entry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Exit_Date__c</fullName>
        <label>Exit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pride_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pride Applicant</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Tracking Details</relationshipLabel>
        <relationshipName>Tracking_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tracking__c</fullName>
        <label>Tracking</label>
        <referenceTo>Tracking__c</referenceTo>
        <relationshipLabel>Tracking Details</relationshipLabel>
        <relationshipName>Tracking_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tracking Detail</label>
    <nameField>
        <displayFormat>TD-{00000}</displayFormat>
        <label>Tracking Details Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracking Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DataFactory_TEST.cls
//Create Test Data

@isTest
public class DataFactory_TEST {

public static Cohort__c CreateTestCohort (Boolean bCreate) {
Cohort__c coh = new Cohort__c();
if (bCreate) {
insert coh;
}
return coh;
}


public static Case CreateTestCase (Id cohortId, Boolean bCreate) {
Case nlc = new Case();
insert nlc;
nlc.Cohort__c = 'Test 1';
update nlc;
return nlc;
}

public static  Projects__c CreateTestProject (Id cohortId, Boolean bCreate) {

Projects__c np = new Projects__c (Cohort__c = cohortId, Name='Test 1', Dashboard_Id__c = '0');
if (bCreate) {
insert np;
}
return np;
}

public static  List<Tracking_Details__c> CreateTestTracking (Id caseId) {
Tracking__c track = new Tracking__c (Name = 'Track Test', Display_Order__c = 0, Dash_Table__c = true);
insert track;

Tracking_Details__c [] testtd = new List<Tracking_Details__c> ();
testtd.add(new Tracking_Details__c(Tracking__c = track.id, entry_date__c = system.today(), Pride_Application__c = caseId));
testtd.add(new Tracking_Details__c(Tracking__c = track.id, entry_date__c = system.today(), exit_date__c = system.today(),Pride_Application__c = caseId));
insert testtd;
return testtd;
}

public static  void SetupTestTracking () {
List<Tracking__c> testTracks = new List<Tracking__c>();
testTracks.add(new Tracking__c(Name = 'Lead', Reference_Name__c = 'Pride Lead'));
testTracks.add(new Tracking__c(Name = 'Expressions of Interest (EOI)', Reference_Name__c = 'EOI'));
testTracks.add(new Tracking__c(Name = 'Application', Reference_Name__c = 'Application'));

insert testTracks;
}

public static void setupCountries() {

List<PADefaults__c> def = new List<PADefaults__c> ();
def.add(new PADefaults__c(Name = 'test1', Picklist_Values__c = '--None--', Cohort__c = 'Guad9;Default', No_Salutation_Error_Msg__c = 'Test', No_Country_Error__c = 'Test CE', No_Org_Type_Error_Msg__c = 'TESTNO'));
insert def;

List<Countries__c> csettings = new List<Countries__c> ();
csettings.add(new Countries__c(Name= 'USA',Cohorts__c = 'Guad9', Country__c = 'USA', Sort_Order__c = 1));
insert csettings;
   
}


}