src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Campaign_Manager_Bio_Long__c</fullName>
        <label>Campaign Manager Bio Long</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Campaign_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign Manager</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Campaign Manager Applicant</relationshipLabel>
        <relationshipName>Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Campaign_Manager_Bio_L__c</fullName>
        <label>Campaign Manager Bio</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Contact for Rare</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/bfc_testcmbiotrigger.cls
@istest
class bfc_testcmbiotrigger {

//Set up data
static testmethod void bfc_test_controller() {

Account taccount = new Account (Name = 'PA Test Trigger');
insert taccount;

Contact tcontact = new Contact();
tcontact.LastName = 'Test PA Con 1';
tcontact.Email = 'testtc1@bfcclient.com';
tcontact.MailingStreet = 'Test Street 1';
tcontact.MailingCity = 'Test City 1';
tcontact.MailingState = 'VA';
tcontact.MailingPostalCode = '22201';
tcontact.MailingCountry = 'USA';
tcontact.Campaign_Manager_Bio_L__c = 'Test Long Bio Update';
tcontact.accountId = taccount.Id;
insert tcontact;

Case tcase = new Case();

tcase.Campaign_Manager__c = tcontact.Id;
insert tcase;

//check bio is updated on Case
Case tconfirm = [Select Id, Campaign_Manager_Bio_Long__c from Case where Id = :tcase.Id];
system.assertequals('Test Long Bio Update',tconfirm.Campaign_Manager_Bio_Long__c);

//Update Bio on Contact and check bio stays same on Case
tcontact.Campaign_Manager_Bio_L__c = 'Test Long Bio Update U2';
update tcontact;

tconfirm = [Select Id, Campaign_Manager_Bio_Long__c from Case where Id = :tcase.Id];
system.assertequals('Test Long Bio Update',tconfirm.Campaign_Manager_Bio_Long__c);

//Set case cm bio back to null, and check now updated again
tcase.Campaign_Manager_Bio_Long__c = null;
update tcase;

tconfirm = [Select Id, Campaign_Manager_Bio_Long__c from Case where Id = :tcase.Id];
system.assertequals('Test Long Bio Update U2',tconfirm.Campaign_Manager_Bio_Long__c);

tcase.Status = 'Rejected';
update tcase;

tcase.Campaign_Manager_Bio_Long__c = null;
update tcase;

//Check bio not updated when case closed
tconfirm = [Select Id, Campaign_Manager_Bio_Long__c from Case where Id = :tcase.Id];
system.assertequals(null,tconfirm.Campaign_Manager_Bio_Long__c);

}

} //end class