src/objects/Cohort__c.object
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Cohort__c</fullName>
        <formula>IF (LEN(Web_Cohort__c) &gt; 0, 
Case (Web_Cohort__c,
&quot;PEP&quot;, &quot;PEP Future&quot;,
&quot;China&quot;, &quot;China Future&quot;,
&quot;Guad&quot;, &quot;Guad Future&quot;,
&quot;Bogor&quot;, &quot;Bogor Future&quot;,
&quot;No Cohort Assigned&quot;
)
,
Case( text(Applying_for_Program_at__c) , 
&quot;Bogor Agricultural University, Indonesia (Bahasa Indonesia)&quot;, Case( text(Date_Seeking_Admission__c) , &quot;February 2010&quot;, &quot;Bogor 4&quot;,&quot;February 2011&quot;, &quot;Bogor 5&quot;,&quot;February 2012&quot;, &quot;Bogor 6&quot;,&quot;Lead Cohort Unknown&quot; ), 
&quot;University of Guadalajara, Mexico (Spanish)&quot;,Case( text(Date_Seeking_Admission__c) , &quot;February 2010&quot;, &quot;Guad 8&quot;,&quot;February 2011&quot;, &quot;Guad 9&quot;,&quot;February 2012&quot;, &quot;Guad 10&quot;,&quot;Lead Cohort Unknown&quot; ), 
&quot;Southwest Forestry University, China (Mandarin Chinese)&quot;,Case( text(Date_Seeking_Admission__c) , &quot;February 2010&quot;, &quot;China 2&quot;,&quot;February 2011&quot;, &quot;China 3&quot;,&quot;February 2012&quot;, &quot;China 4&quot;,&quot;Lead Cohort Unknown&quot; ), 
&quot;Georgetown University, USA (English)&quot;,Case( text(Date_Seeking_Admission__c) , &quot;February 2010&quot;, &quot;PEP 2&quot;,&quot;February 2011&quot;, &quot;PEP 3&quot;,&quot;February 2012&quot;, &quot;PEP 4&quot;,&quot;Lead Cohort Unknown&quot; ), 
&quot;Lead Cohort Unknown&quot; 
)
)</formula>
        <label>Cohort</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Web_Cohort__c</fullName>
        <description>As captured from EOI form</description>
        <label>Web Cohort</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <businessProcess>Lead Process</businessProcess>
        <description>Standard Lead - donors,orgs, etc</description>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/PADefaults__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To store defaults for PA form picklists</description>
    <fields>
        <fullName>Cohort__c</fullName>
        <label>Cohort</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Country_Error__c</fullName>
        <label>No Country Error</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Org_Type_Error_Msg__c</fullName>
        <label>No Org Type Error Msg</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_Salutation_Error_Msg__c</fullName>
        <label>No Salutation Error Msg</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Picklist_Values__c</fullName>
        <label>Picklist Values</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>PA Defaults</label>
</CustomObject>

src/classes/LeadExtension.cls
public with sharing class LeadExtension {

    private final Lead geneoi;
    
    public LeadExtension (ApexPages.StandardController controller) {
        this.geneoi = (Lead)controller.getRecord();
    }

//Confirmation page is the same page with just one section visible - this controls that visibility    
    Boolean showconfirmation = false;
//We pass in the cohort to enable certain dropdowns to be cohort specific    
    String cohort;
    List<SelectOption> options;
    List<SelectOption> optionsal;
    List<SelectOption> optionotype;
    String PickDefault;
    List<String> custompickerrors = new String[3];
          

//set the boolean for the render value
public Boolean getshowconfirmation() {
return showconfirmation;
}

//cohort is passed in - but if there is none, display default values
public String getcohort() {
if (ApexPages.currentPage().getParameters().get('cht') != null) {
cohort = ApexPages.currentPage().getParameters().get('cht');
}
else 
{cohort = 'Default';}
return cohort;
}


//Different cohorts have different options (e.g. a Spanish form could still need to present different countries for different cohorts)
//So we store lists in custom settings

public String getPickDefault(){
if (PickDefault == null)
{
List<PADefaults__c> def = PADefaults__c.getall().values();
for (PADefaults__c d: def) {
if (d.cohort__c.contains(getcohort())) {
PickDefault = d.Picklist_Values__c;
custompickerrors[0] = d.No_Salutation_Error_Msg__c;
custompickerrors[1] = d.No_Country_Error__c;
custompickerrors[2] = d.No_Org_Type_Error_Msg__c;
}
}
}
return PickDefault; 
}

public List<SelectOption> getCountries(){
if (options == null) {
options = EOIDefaults.getCountries(getPickDefault(), getcohort());
}
return options; 
}

public List<SelectOption> getSalutations(){
if (optionsal == null) {
optionsal = EOIDefaults.getSalutations(getPickDefault(), getcohort());
}
return optionsal; 
}

public List<SelectOption> getOrgTypes(){
if (optionotype == null) {
optionotype = EOIDefaults.getOrgTypes(getPickDefault(), getcohort());
}
return optionotype; 
}

public PageReference save(){
          geneoi.RecordTypeId = '01230000000541C';
          geneoi.Web_Cohort__c = getcohort();
            Database.DMLOptions opts = new Database.DMLOptions();
            opts.EmailHeader.triggerAutoResponseEmail = true;
            opts.EmailHeader.triggerUserEmail = true;
            opts.assignmentRuleHeader.useDefaultRule= true;
            geneoi.setOptions(opts);
          insert geneoi;
          showconfirmation = true;
          return null;
}

 
}// end all