src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Implementing Partner Key Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decision Maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deferred Campaign Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Director</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supervisor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>University Professor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alumni</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Prospect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lapsed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Choice__c.object
<CustomObject>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Questions</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Question Choices</relationshipLabel>
        <relationshipName>Question_Choices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Question Choice</label>
    <nameField>
        <label>Question Choices Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Choices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Question_Choice_Selection__c.object
<CustomObject>
    <fields>
        <fullName>RARE_Campaign__c</fullName>
        <formula>Scorecard_Answer__r.Scorecard__r.RARE_Campaign__r.Name</formula>
        <label>RARE Campaign</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scorecard_Answer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Scorecard Answer</label>
        <referenceTo>Scorecard_Answer__c</referenceTo>
        <relationshipLabel>Question Choices Selections</relationshipLabel>
        <relationshipName>Question_Choices_Selections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question Choice Selection</label>
    <nameField>
        <displayFormat>QCS-{000000}</displayFormat>
        <label>Question Choice Selection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Choices Selections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Questions__c.object
<CustomObject>
    <description>QuestionsObject</description>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Questions</label>
    <nameField>
        <label>Qs ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RARE_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>IMPLEMENTATION</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>COMPLETE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANCELLED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INCOMPLETE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTNERS WITHDREW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Rare Campaign</label>
    <nameField>
        <label>Rare Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rare Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scorecard__c.object
<CustomObject>
    <description>This is the ScorecardObject</description>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RARE_Campaign__c</fullName>
        <label>RARE Campaign</label>
        <referenceTo>RARE_Campaign__c</referenceTo>
        <relationshipLabel>Scorecards</relationshipLabel>
        <relationshipName>Score_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission_Date__c</fullName>
        <label>Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submission_Status__c</fullName>
        <description>Set by Submission Process</description>
        <inlineHelpText>Set by Submission Process</inlineHelpText>
        <label>Submission Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Send Submission Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submission Email Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Scorecard</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Score Card ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Scorecard_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>Display Order on Scorecard Page</inlineHelpText>
        <label>Display Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Type2__c</fullName>
        <label>Question Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Questions</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Scorecard Answers</relationshipLabel>
        <relationshipName>Scorecard_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RARE_Campaign__c</fullName>
        <formula>Scorecard__r.RARE_Campaign__r.Name</formula>
        <label>RARE Campaign</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scorecard__c</fullName>
        <label>Scorecard</label>
        <referenceTo>Scorecard__c</referenceTo>
        <relationshipLabel>Scorecard Answers</relationshipLabel>
        <relationshipName>Scorecard_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Select_QC_Ids__c</fullName>
        <label>Select QC Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Scorecard Answer</label>
    <nameField>
        <displayFormat>SCA-{000000}</displayFormat>
        <label>Scorecard Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Scorecard_Submission__c.object
<CustomObject>
    <fields>
        <fullName>Email_Address__c</fullName>
        <inlineHelpText>Set from Team Role, but can be overridden</inlineHelpText>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Submitter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approver</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Scorecard__c</fullName>
        <label>Scorecard</label>
        <referenceTo>Scorecard__c</referenceTo>
        <relationshipLabel>Scorecard Submissions</relationshipLabel>
        <relationshipName>Scorecard_Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Sent to Submitters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Team_Roles__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Roles</label>
        <referenceTo>Team_Roles__c</referenceTo>
        <relationshipLabel>Scorecard Submissions</relationshipLabel>
        <relationshipName>Scorecard_Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scorecard Submission</label>
    <nameField>
        <displayFormat>SUBMS-{0000}</displayFormat>
        <label>Scorecard Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Team_Roles__c.object
<CustomObject>
    <description>Rare staff roles for campaigns -- developing for PSC workflow</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this team member still active in this role for the campaign/cohort/etc.?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <formula>Member_Name__r.Email</formula>
        <inlineHelpText>To display current email address of Team Member - used for scorecard submission alerts</inlineHelpText>
        <label>Email Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Who is on this team?</inlineHelpText>
        <label>Member Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Team Roles</relationshipLabel>
        <relationshipName>Team_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rare_Campaign__c</fullName>
        <description>Campaign this user is associated with</description>
        <label>Rare Campaign</label>
        <referenceTo>RARE_Campaign__c</referenceTo>
        <relationshipName>Campaign_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Scorecard_Role__c</fullName>
        <formula>CASE( Member_Type__c,
&quot;Monitoring Specialist&quot;, &quot;Submitter&quot;,
&quot;Program Manager&quot;, &quot;Submitter&quot;,
&quot;Cohort Director&quot;, &quot;Approver&quot;,
&quot;&quot;)</formula>
        <inlineHelpText>Determines if Campaign Member is required to receive notification of new scorecard</inlineHelpText>
        <label>Scorecard Role</label>
        <type>Text</type>
    </fields>
    <label>Team Roles</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScorecardProcessHandler.cls
public class ScorecardProcessHandler {

private List<RARE_Campaign__c> scorecampaigns;
private List<Scorecard__c> newscorecards;

public void GenerateNewScorecards (List<Id> camps) {

scorecampaigns = [Select Id, Name, 
(Select Id, Name FROM Score_Cards__r Order By Submission_Date__c DESC NULLS LAST LIMIT 1),
(Select Id, Member_Name__c, Member_Name__r.Email, Scorecard_Role__c FROM Campaign_Roles__r WHERE Active__C = TRUE AND Scorecard_Role__c IN ('Submitter', 'Approver') )
FROM RARE_Campaign__c WHERE Id IN :camps];

Set<Id> scorecardstocopy = new Set<Id>();
for (RARE_Campaign__c scamp: scorecampaigns) {

    if (scamp.Score_Cards__r.isEmpty() == FALSE) {
        scorecardstocopy.add(scamp.Score_Cards__r[0].Id);
    }

}

newscorecards = new List<Scorecard__c> ();
List< Scorecard_Answer__c > newscorecardanswers = new List< Scorecard_Answer__c > ();


List<Scorecard__c> oldscorecards = [Select Id, Name, Comment__c, RARE_Campaign__c,
(Select Id, Questions__c, Select_QC_Ids__c, Question_Type2__c, Display_Order__c from Scorecard_Answers__r Order BY Display_Order__c ASC)
    FROM Scorecard__c
    WHERE Id IN :scorecardstocopy];    

for (Scorecard__c osc: oldscorecards) {

    Scorecard__c nsc = new Scorecard__c(RARE_Campaign__c = osc.RARE_Campaign__c, Status__c = 'Active', RecordTypeId = '012800000007kFG');
    newscorecards.add(nsc);
    
        for (Scorecard_Answer__c sca: osc.Scorecard_Answers__r) {
            Scorecard_Answer__c scatemp = new Scorecard_Answer__c();
            scatemp.RecordTypeId = '012800000007kFE';
            scatemp.Scorecard__r = nsc;
            scatemp.Questions__c = sca.Questions__c;
            scatemp.Select_QC_Ids__c = sca.Select_QC_Ids__c;
            scatemp.Display_Order__c = sca.Display_Order__c;
            scatemp.Question_Type2__c = sca.Question_Type2__c;
            newscorecardanswers.add(scatemp);
        }
}


insert newscorecards;
for (Scorecard_Answer__c nsca: newscorecardanswers) {
  // is there a relationship to a parent?
                if (nsca.Scorecard__r != null) {
                    nsca.Scorecard__c = nsca.Scorecard__r.Id; 
                }
}

insert newscorecardanswers;

}

public void generateSubmissionNotice() {
List<Scorecard_Submission__c> NewScorecardSubmissions = new List<Scorecard_Submission__c>();

Map<Id, RARE_Campaign__c> scorecampaigns = new Map<Id, RARE_Campaign__c> (scorecampaigns);

for (Scorecard__c newsc: newscorecards) {
newsc.Submission_Status__c = 'Send Submission Email';
    if (scorecampaigns.containskey(newsc.RARE_Campaign__c) ) {
        RARE_Campaign__c temprc = scorecampaigns.get(newsc.RARE_Campaign__c);
        if (temprc.Campaign_Roles__r.isEmpty() == FALSE) {
        
        for (Team_Roles__c tc: temprc.Campaign_Roles__r) {
            Scorecard_Submission__c ssub = new Scorecard_Submission__c();
            ssub.Scorecard__c = newsc.Id;
            ssub.Role__c = tc.Scorecard_Role__c;
            ssub.Team_Roles__c = tc.Id;
            ssub.Email_Address__c = tc.Member_Name__r.Email;
            NewScorecardSubmissions.add(ssub);
        }
        
        }
    
    }
     
}

insert NewScorecardSubmissions;
update newscorecards;
}

public class ScorecardAnswerSetup {
public Scorecard_Answer__c sa {get;set;}
public Questions__c saquestion {get;set;}
public Boolean bInclude {get;set;}

public ScorecardAnswerSetup (Integer iDisplayOrder, Questions__c question ) {

sa = new Scorecard_Answer__c();
sa.Questions__c = question.Id;
saquestion = question;
sa.Display_Order__c = iDisplayOrder;
}
}

public static List<Questions__c> getAllQuestions () {
    return [Select Id, Name, Question_Text__c FROM Questions__c WHERE RecordTypeId = '012800000007kFC' ORDER By NAME ASC];
}

public static void setAnswerChoices(List<Id> scorecardsIds) {
          Map<Id, Question_Choice__c> qcmap = new Map<Id, Question_Choice__c> ( [Select Id, Points__c FROM Question_Choice__c]);
        
          List<Scorecard_Answer__c> sa = [Select Id, Select_QC_Ids__c from Scorecard_Answer__c WHERE Scorecard__c IN :scorecardsIds];
          List<Question_Choice_Selection__c> questionchoices = new List<Question_Choice_Selection__c>();  
          
          for (Scorecard_Answer__c satemp: sa) {
            List<String> sChoices;
            Decimal iScore = 0;
            if (satemp.Select_QC_Ids__c != NULL) {
                sChoices = satemp.Select_QC_Ids__c.split(';');
                for (String s: sChoices) {
                    if (qcMap.containskey(s)) {
                       iScore += qcmap.get(s).Points__c;
                           String sKey = satemp.Id + ':' + s;
                           questionchoices.add(new Question_Choice_Selection__c(Scorecard_Answer__c = satemp.Id, Question_Choice__c = s, Key__c = sKey));
                    }
               }
           }
           
           satemp.Score__c = iScore;
               }
          
         update sa;
         upsert questionchoices key__c;
        
    }

}