src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contact</fullName>
        <active>true</active>
        <description>Contact for Rare</description>
        <label>Contact</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Question_Choice__c.object
<CustomObject>
    <fields>
        <fullName>Option_Text__c</fullName>
        <label>Option Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Questions</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Question Choices</relationshipLabel>
        <relationshipName>Question_Choices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Question Choice</label>
    <nameField>
        <label>Question Choices Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Choices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questions__c.object
<CustomObject>
    <description>QuestionsObject</description>
    <fields>
        <fullName>Answer_Type__c</fullName>
        <label>Answer Type</label>
        <picklist>
            <picklistValues>
                <fullName>radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Questions</label>
    <nameField>
        <label>Qs ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RARE_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Primary_PPM__c</fullName>
        <description>Primary Pride Program Manager (will be a lookup in production)</description>
        <inlineHelpText>Who is this campaign&apos;s PPM? (Last, First)</inlineHelpText>
        <label>Primary PPM</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipName>RARE_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Start date for a campaign</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Rare Campaign</label>
    <nameField>
        <label>Rare Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rare Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scorecard__c.object
<CustomObject>
    <description>This is the ScorecardObject</description>
    <fields>
        <fullName>RARE_Campaign__c</fullName>
        <label>RARE Campaign</label>
        <referenceTo>RARE_Campaign__c</referenceTo>
        <relationshipLabel>Scorecards</relationshipLabel>
        <relationshipName>Score_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Scorecard</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Score Card ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Scorecard_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Display_Order__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>Display Order on Scorecard Page</inlineHelpText>
        <label>Display Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <formula>Questions__r.Question_Text__c</formula>
        <label>Question Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Questions</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Scorecard Answers</relationshipLabel>
        <relationshipName>Scorecard_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RARE_Campaign__c</fullName>
        <formula>Scorecard__r.RARE_Campaign__r.Name</formula>
        <label>RARE Campaign</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scorecard__c</fullName>
        <label>Scorecard</label>
        <referenceTo>Scorecard__c</referenceTo>
        <relationshipLabel>Scorecard Answers</relationshipLabel>
        <relationshipName>Scorecard_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Select_QC_Ids__c</fullName>
        <label>Select QC Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Scorecard Answer</label>
    <nameField>
        <displayFormat>SCA-{000000}</displayFormat>
        <label>Scorecard Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Scorecard_Submission__c.object
<CustomObject>
    <fields>
        <fullName>Scorecard__c</fullName>
        <label>Scorecard</label>
        <referenceTo>Scorecard__c</referenceTo>
        <relationshipLabel>Scorecard Submissions</relationshipLabel>
        <relationshipName>Scorecard_Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Team_Roles__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Team Roles</label>
        <referenceTo>Team_Roles__c</referenceTo>
        <relationshipLabel>Scorecard Submissions</relationshipLabel>
        <relationshipName>Scorecard_Submissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Scorecard Submission</label>
    <nameField>
        <displayFormat>SUBMS-{0000}</displayFormat>
        <label>Scorecard Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Team_Roles__c.object
<CustomObject>
    <description>Rare staff roles for campaigns -- developing for PSC workflow</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this team member still active in this role for the campaign/cohort/etc.?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Member_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Who is on this team?</inlineHelpText>
        <label>Member Name</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Team Roles</relationshipLabel>
        <relationshipName>Team_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Member_Type__c</fullName>
        <description>The specific role for this user for the specified campaign/cohort/etc.</description>
        <label>Member Type</label>
        <picklist>
            <picklistValues>
                <fullName>Monitoring Specialist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cohort Director</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rare_Campaign__c</fullName>
        <description>Campaign this user is associated with</description>
        <label>Rare Campaign</label>
        <referenceTo>RARE_Campaign__c</referenceTo>
        <relationshipName>Campaign_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Date the team member start his/her role with this campaign/cohort/etc.</description>
        <inlineHelpText>When did the team member start his/her role with this campaign/cohort/etc.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Team Roles</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Role ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Team Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScorecardTracker_TESTS.cls
@isTest
private class ScorecardTracker_TESTS{

//@testSetup
//private static void setupScorecardData() {

@isTest
private static void NewScorecardProcess() {

List<Questions__c> tquestions = new List<Questions__c>();
tquestions.add(new Questions__c(Name = 'Q1', Answer_Type__c = 'radio', Question_Text__c = 'q 123', RecordTypeId = '012800000007kFC'));
tquestions.add(new Questions__c(Name = 'Q2', Answer_Type__c = 'radio', Question_Text__c = 'q 456', RecordTypeId = '012800000007kFC'));
tquestions.add(new Questions__c(Name = 'Q3', Answer_Type__c = 'checkbox', Question_Text__c = 'q 789', RecordTypeId = '012800000007kFC'));

insert tquestions;

List<Question_Choice__c> testqc = new List<Question_Choice__c> ();


for (Questions__c q: tquestions) {

    for (integer i= 1; i<4; i++) {
        testqc.add(new Question_Choice__c(Order__c = 1, Points__c = i, Option_Text__c = 'Test O' + i, Questions__c = q.id));
    }

}

insert testqc;

Program__c tprogram = new Program__c (Name = 'Test Program');
insert tprogram;

RARE_Campaign__c tcampaign = new RARE_Campaign__c(Name = 'Test Campaign 1', Program__c = tprogram.Id, Primary_PPM__c = 'Test');
insert tcampaign;

Account tRareAccount = new Account (Name = 'T Rare');
insert tRareAccount;

List<Contact> cons = new List<Contact> ();
cons.add(new Contact (LastName = 'MS', FirstName = 'Test1', AccountId = tRareAccount.Id, Email = 'rare1@bfcclient.com'));
cons.add(new Contact (LastName = 'PM', FirstName = 'Test2', AccountId = tRareAccount.Id, Email = 'rare2@bfcclient.com'));
cons.add(new Contact (LastName = 'CD', FirstName = 'Test3', AccountId = tRareAccount.Id, Email = 'rare3@bfcclient.com'));

insert cons;


List<Team_Roles__c> testr = new List<Team_Roles__c>();
testr.add(new Team_Roles__c(Member_Name__c = cons[0].Id, Rare_Campaign__c = tcampaign.Id, Start_Date__c = system.today(), Active__c = TRUE, Member_Type__c = 'Monitoring Specialist'));
testr.add(new Team_Roles__c(Member_Name__c = cons[1].Id, Rare_Campaign__c = tcampaign.Id, Start_Date__c = system.today(), Active__c = TRUE, Member_Type__c = 'Program Manager'));
testr.add(new Team_Roles__c(Member_Name__c = cons[2].Id, Rare_Campaign__c = tcampaign.Id, Start_Date__c = system.today(), Active__c = TRUE, Member_Type__c = 'Cohort Director'));
insert testr;

SetupNewScoreCardExtension setupnsc = new SetupNewScoreCardExtension(new ApexPages.StandardController(tcampaign));
//Add Questions
for (ScorecardProcessHandler.ScorecardAnswerSetup sap: setupnsc.NewScoreCardAnswers) {
    sap.bInclude = TRUE;
}
//Generate Template
setupnsc.createScorecard();
setupnsc.SendScorecard();

Map<Id, Questions__c> qmap = new Map<Id, Questions__c> ( [Select Id, Name, Question_Text__c, Answer_Type__c, (Select Order__c, Points__c, Option_Text__c FROM Question_Choices__r Order by Order__c ASC) from Questions__c]);

List<Scorecard__c> scorecards = [Select Id, Name, (Select Id, Questions__c, Select_QC_Ids__c from Scorecard_Answers__r Order BY Display_Order__c ASC) FROM Scorecard__c ORDER BY CREATEDDATE DESC];    

Scorecard_Submission__c sub = [Select Id FROM Scorecard_Submission__c  WHERE Team_Roles__c =  :testr[0].Id];

PageReference scapage = Page.ScoreCardAnswers;
Test.setCurrentPage(scapage); 
ApexPages.currentPage().getParameters().put('scid', scorecards[1].Id);
ApexPages.currentPage().getParameters().put('trid', sub.Id);

ScorecardAnswerController testsac = new ScorecardAnswerController();
//Now submit via async remote action

String sAnswerValues = '';

for (Scorecard_Answer__c sca: scorecards[0].Scorecard_Answers__r) {
Questions__c q = qmap.get(sca.Questions__c);
List<Question_Choice__c> qctemp = q.Question_Choices__r; 
sAnswerValues += sca.Id + ':' + qctemp[0].Id + ','; 
}

List<String> sValues = new List<String>();
sValues.add(scorecards[1].Id);
sValues.add('green');
sValues.add('A Comment for the ages');

//Save
ScorecardAnswerController.ReceiveUpdates(sAnswerValues, 'Save', sValues);

//Submit
ScorecardAnswerController.ReceiveUpdates(sAnswerValues, 'Submit', sValues);

sValues.add('An Approver Comment for the ages');    
//Approve
ScorecardAnswerController.ReceiveUpdates(sAnswerValues, 'Approve', sValues);
    
    /*
    public transient List<ScorecardAnswerWrapper> SAW {get;set;}
    public transient Scorecard__c score {get;set;}
    public String scid {get;set;}
    public String teamid {get;set;}
    private Scorecard_Submission__c user;
    public String sNewValues {get;set;}
    public Boolean bShowSubmit {get;set;} 
    public Boolean bShowApprove {get;set;} 
    */    
   

}


}