src/objects/CT_Access_Credentials__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Access Creds for Campaign Tracker Access</description>
    <fields>
        <fullName>Basic_Token__c</fullName>
        <inlineHelpText>For use where Basic Auth is available</inlineHelpText>
        <label>Basic Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_URI__c</fullName>
        <label>Default URI</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response__c</fullName>
        <label>Response</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>cnonce__c</fullName>
        <label>cnonce</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nc__c</fullName>
        <label>nc</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>nonce__c</fullName>
        <label>nonce</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>qop__c</fullName>
        <label>qop</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>realm__c</fullName>
        <label>Realm</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>CT Access Credentials</label>
</CustomObject>

src/classes/MongoDatabaseAccess.cls
public class MongoDatabaseAccess {

public String sEndPoint {get;set;}
public Boolean bSuccess {get;set;}
public String sResponse {get;set;}
    
    
    public void Execute () {
        bSuccess = FALSE;
        HTTP http = new HTTP();
        HTTPRequest req = new HTTPRequest();
        req.setMethod('GET');
      
        system.debug(sEndPoint);
      
        req.setEndpoint(sEndPoint);
        String sHeader = getAuthHeader();
      
        req.setHeader('Authorization', sHeader);
        try {
            HttpResponse res = http.send(req);
            //System.debug('MONGO Response' + res.getBody());
                if (res.getStatusCode() == 200) {
                bSuccess = TRUE;
                    String sJson = res.getBody();
                    sJson = sJson.replace('_id', 'sid');
                    sJson = sJson.replace('$', 'x');
                    sResponse = sJSON;
                   }
                else {
                sResponse = res.getStatus();    
                }
            }   
        Catch (Exception Ex) {
            sResponse = Ex.getMessage();
        }
    }
    
    private String getAuthHeader() {
        CT_Access_Credentials__c ctcreds = CT_Access_Credentials__c.getinstance();
        String sHeader;
        /*
        String sHeader = 'Digest ';
        sHeader += 'username="' + ctcreds.Username__c + '", ';
        sHeader += 'realm="' + ctcreds.realm__c + '", ';
        sHeader += 'nonce="' + ctcreds.nonce__c + '", ';
        sHeader += 'uri="' + ctcreds.Default_URI__c + '", ';
        sHeader += 'qop=' + ctcreds.qop__c + ', ';
        sHeader += 'nc=' + ctcreds.nc__c + ', ';
        sHeader += 'cnonce="' + ctcreds.cnonce__c + '", ';
        sHeader += 'response="' + ctcreds.Response__c + '", ';
        sHeader += 'opaque=""';
        */
        sHeader = 'Basic ' + ctcreds.Basic_Token__c;
        //system.debug(sHeader);
        return sHeader;   
    }

    public Integer getCount(String sCollection) {
    sEndPoint = 'https://mongodb.rare.org/rarect_prod/$cmd/?filter_count=' + sCollection +'&limit=1';
    Execute ();
    if (bSuccess) {
        MongoCollectionCount mc = MongoCollectionCount.parse(sResponse);
        return mc.rows[0].n;
    }
    return 0;
    }


}