src/objects/Flash_Card__c.object
<CustomObject>
    <description>This is the FlashCardObject</description>
    <fields>
        <fullName>RARE_Campaign__c</fullName>
        <label>RARE Campaign</label>
        <referenceTo>RARE_Campaign__c</referenceTo>
        <relationshipLabel>Flash Cards</relationshipLabel>
        <relationshipName>Flash_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Flash Card</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Flash Card ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flash Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Milestone__c.object
<CustomObject>
    <description>MilestoneObject</description>
    <fields>
        <fullName>RARE_Campaign__c</fullName>
        <label>RARE Campaign</label>
        <referenceTo>RARE_Campaign__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Milestones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Milestone ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RARE_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Project_Code__c</fullName>
        <description>Are project codes predetermined or a la carte?</description>
        <label>Project Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Rare Campaign</label>
    <nameField>
        <label>Rare Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rare Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MongoCampaignParserController.cls
public with sharing class MongoCampaignParserController {
private final Rare_Campaign__c rcampaign;
    public MongoCampaignParserController(ApexPages.StandardController controller) {
    rcampaign = (Rare_Campaign__c)controller.getrecord();
    }

public CampaignsParser_CT cpct {get;set;}
public MongoDatabaseAccess mda {get;set;}
public Rare_Campaign__c rc {get;set;}
public List<Milestone__c> milestones {get;set;}
public List<Flash_Card__c> flashcards {get;set;}
public Boolean bSuccess {get;set;}

public pageReference ReturntotRC() {
return new PageReference('/' + rcampaign.Id);
}


public PageReference parseData() {
try {
mda = new MongoDatabaseAccess();
mda.sEndPoint = 'https://mongodb.rare.org/rarect_prod/campaigns/?filter_project_code=' + rcampaign.Project_code__c + '&limit=-1';
mda.execute();
system.debug(mda.sResponse);
if (mda.bSuccess) {
    cpct = new CampaignsParser_CT();
    cpct.parsedata(mda.sResponse);
    cpct.updatecampaigns();
}
}
Catch (Exception Ex) {
}
return null;
}



}