src/objects/Projects__c.object
<CustomObject>
    <description>Conservation projects</description>
    <fields>
        <fullName>Dashboard_Id__c</fullName>
        <description>Used to generate Cohort specific dashboard data</description>
        <inlineHelpText>Do not use - admin only</inlineHelpText>
        <label>Dashboard Id</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <label>Projects</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Dash_Cohort_to_Date__c</fullName>
        <inlineHelpText>For VF Dashboard Only</inlineHelpText>
        <label>Dash Cohort to Date</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dash_Completed__c</fullName>
        <inlineHelpText>For use on Dashboard VF pages</inlineHelpText>
        <label>Dash Completed</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dash_Current__c</fullName>
        <inlineHelpText>For use on Dashboard VF pages</inlineHelpText>
        <label>Dash Current</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dash_Ended__c</fullName>
        <inlineHelpText>For use on Dashboard VF pages</inlineHelpText>
        <label>Dash Ended</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dash_Table__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show in Dash Table?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Stage__c</fullName>
        <formula>text(Display_Order__c)  &amp;&quot; : &quot; &amp; Name</formula>
        <label>Display Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reference_Name__c</fullName>
        <description>To enable easy lookup against stage names, we can store the related lead/application stage in this field</description>
        <label>Reference Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Tracking</label>
    <nameField>
        <label>Stage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tracking_Details__c.object
<CustomObject>
    <fields>
        <fullName>Application_Cohort__c</fullName>
        <formula>if(Len( Pride_Application__c) &gt;0, 
Text( Pride_Application__r.Cohort__c ),  
if(Len( Pride_Lead__c) &gt;0, 
Pride_Lead__r.Cohort__c, 
Contact__r.Cohort__c )
)</formula>
        <label>Cohort</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(

NOT((ISNULL(Exit_Date__c))) , &quot;Completed&quot;,

If (len( Key_Status__c ) &gt; 0, 

if (LEN(Application_Recommendationt__c) = 0,

&quot;Current&quot;,

Case(Application_Recommendationt__c,
&quot;Recommended&quot;,&quot;Current&quot;,
&quot;Deferred&quot;,&quot;Ended&quot;,
&quot;Rejected&quot;,&quot;Ended&quot;,
&quot;Current&quot;)),

Case( Lead_Status_Tracking__c ,
&quot;EOI Not Screened&quot;,&quot;Current&quot;,
&quot;Qualified&quot;,&quot;Complete&quot;,
&quot;Unqualified&quot;,&quot;Ended&quot;,
&quot;Contacted&quot;,&quot;Current&quot;,
&quot;Open&quot;,&quot;Current&quot;,
&quot;Current&quot;) )

)</formula>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tracking__c</fullName>
        <label>Tracking</label>
        <referenceTo>Tracking__c</referenceTo>
        <relationshipLabel>Tracking Details</relationshipLabel>
        <relationshipName>Tracking_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Tracking Detail</label>
    <nameField>
        <displayFormat>TD-{00000}</displayFormat>
        <label>Tracking Details Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tracking Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/bfc_cohortdashboardscontroller.cls
public class bfc_cohortdashboardscontroller {

   private final string spage;
   private final string scode;
   string cohort;
    public list<Tracking__c> cohorttracking = new List<Tracking__c>();
      
    public bfc_cohortdashboardscontroller() {
            spage = ApexPages.currentPage().getUrl();
            Integer sstart =  spage.indexOf('_', 0);
            Integer send =  spage.indexOf('?', 0);
            scode = spage.substring(sstart + 1,send);
            }

    public String getscode() {
            return scode;
      }
      
public String getcohort() {
   getscode();
   cohort = [Select Name From Projects__c WHERE Dashboard_Id__c = :scode].Name;
   return cohort;
   }

public list<Tracking__c> getcohorttracking() {

cohorttracking = [Select Reference_Name__c, Display_Stage__c, Dash_Ended__c, Dash_Current__c, Dash_Completed__c,Dash_Cohort_to_Date__c, (Select Tracking__c, Status__c From Tracking_Details__r where Application_Cohort__c = :getcohort()) From Tracking__c where Dash_Table__c = true order by Display_Stage__c ASC];

For (Tracking__c t: cohorttracking) {
Integer dCurrent = 0;
Integer dCompleted = 0;
Integer dEnded = 0;
        for (Tracking_Details__c td : t.Tracking_Details__r ) {
            if (td.Status__c == 'Current') {
                dCurrent +=1;
            }
            if (td.Status__c == 'Completed') {
                dCompleted +=1;
            }
            if (td.Status__c == 'Ended') {
                dEnded +=1;
            }
        }   
t.Dash_Current__c = dCurrent;
t.Dash_Completed__c = dCompleted;
t.Dash_Ended__c = dEnded;
if (t.Reference_Name__c == 'Fit Assessment' || t.Reference_Name__c == 'EOI') {
t.Dash_Cohort_to_Date__c = dCurrent + dCompleted + dEnded;
}
else
t.Dash_Cohort_to_Date__c = dCurrent + dCompleted;
}

return cohorttracking;
}

}