src/objects/Project_Funding__c.object
<CustomObject>
    <fields>
        <fullName>Allocated_Amount_Calc__c</fullName>
        <formula>Funding__r.ExpectedRevenue * Allocation__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Allocated Amount Calc</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allocated_Amount__c</fullName>
        <label>Allocated Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allocation__c</fullName>
        <label>% Allocation</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Funding__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N300000026cpxEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Funding</label>
    <nameField>
        <displayFormat>PF-{000000}</displayFormat>
        <label>Project Funding Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Funding</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ManageOpportunities.cls
public class ManageOpportunities {
/* With reference to Steve Andersen's post: http://gokubi.com/archives/two-interesting-ways-to-architect-apex-triggers */ 


public static void isafterupdate(Map<Id, Opportunity> newomap, Map<Id, Opportunity> oldomap ) {

Set<Id> otoprocess = new Set<Id> () ;

for (Id oid : newomap.keyset() ) {
if (newomap.get(oId).expectedrevenue <> oldomap.get(oId).expectedrevenue) {
otoprocess.add(oId);
} 
}


if (otoprocess.size () > 0 ) {

Project_Funding__c [] pftoupdate = [Select Id, Allocation__c, Allocated_Amount__c, Allocated_Amount_Calc__c from project_funding__c where funding__c in :otoprocess];

for (Project_Funding__c pf: pftoupdate) {
//only update when a % is set
    if (pf.Allocation__c != null ) {
        pf.Allocated_Amount__c = pf.Allocated_Amount_Calc__c;
    }
  }
update pftoupdate;
}
}

}