src/objects/Project_Funding__c.object
<CustomObject>
    <fields>
        <fullName>Allocated_Amount__c</fullName>
        <label>Allocated Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allocated_To__c</fullName>
        <label>Allocated To FY</label>
        <picklist>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Funding__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Funding</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N300000026cpxEAA</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project Funding</label>
    <nameField>
        <displayFormat>PF-{000000}</displayFormat>
        <label>Project Funding Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Funding</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Proposal_Team__c.object
<CustomObject>
    <fields>
        <fullName>Funding_Record_Name__c</fullName>
        <label>Funding Record Name</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Proposal Team</relationshipLabel>
        <relationshipName>Proposal_Team</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Percentage_Split__c</fullName>
        <label>Percentage Split</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Proposal Team</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Link to Detail Records</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Proposal_Team_Calc__c.object
<CustomObject>
    <description>Stores Amounts for each Proposal Team Member based on Project Funding, and % Split for each member by Year</description>
    <fields>
        <fullName>Allocated_Amount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Allocated Amount</label>
        <precision>17</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allocated_Year__c</fullName>
        <label>Allocated Year</label>
        <picklist>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>Use this to enable simple update based on unique key of Funding + Team Member + Year</description>
        <externalId>true</externalId>
        <label>Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Proposal_Team__c</fullName>
        <label>Proposal Team</label>
        <referenceTo>Proposal_Team__c</referenceTo>
        <relationshipLabel>Proposal Team Calculations</relationshipLabel>
        <relationshipName>Proposal_Team_Calculations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Proposal Team Calculation</label>
    <nameField>
        <displayFormat>PCN-{000}</displayFormat>
        <label>PCN Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Proposal Team Calculations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/bfc_proposalteamupdate.cls
public class bfc_proposalteamupdate {

@future
public static void updateteamcalc (Set<Id> optysforupdate) {
 triggerhelper.recursiveHelper(true);
Map<Id, Map<String, Decimal>> fundingmap = new Map<Id, Map<String, Decimal>> ();

 AggregateResult[] groupedResults =               
        [SELECT 
        Allocated_To__c at,
        Funding__c fund,
        sum(Allocated_Amount__c) aa
        FROM Project_Funding__c 
        WHERE Funding__c IN :optysforupdate
        GROUP BY Funding__c, Allocated_To__c ];
        
    for (AggregateResult ar : groupedResults)  
    
    {
                Map<String, Decimal> yearmap;       
                    if (fundingmap.containskey( (Id)ar.get('fund') ) ) {
                           yearmap  = fundingmap.get( (Id)ar.get('fund') );
                                                        }
                    else {
                        yearmap  = new Map<String, Decimal> () ;
                    }                       
                    
                    yearmap.put( (String)ar.get('at'), (Decimal)ar.get('aa') );
                    fundingmap.put( (Id)ar.get('fund'), yearmap);
    }
   system.debug(fundingmap);
    
List<Proposal_Team_Calc__c> ptc = new List<Proposal_Team_Calc__c> () ;
Set<String> recordsforcleanup = new Set<String> ();

For (Proposal_Team__c pt: [Select Id, Funding_Record_Name__c, Percentage_Split__c from Proposal_Team__c where Funding_Record_Name__c IN :optysforupdate]) {

if (fundingmap.containskey (pt.Funding_Record_Name__c) ) {
Map <String, Decimal> fyearmap = fundingmap.get( pt.Funding_Record_Name__c );
for (String s: fyearmap.keyset() ) {
String skey = String.valueof(pt.Funding_Record_Name__c) + String.valueOf(pt.Id) + s; 
recordsforcleanup.add(skey);
ptc.add (new Proposal_Team_Calc__c (Proposal_Team__c = pt.Id, Allocated_Year__c = s, Allocated_Amount__c =  ( fyearmap.get(s) *  pt.Percentage_Split__c ) / 100, key__c = skey ) );
}
} //end if

} //end loop
upsert ptc key__c;

//clean up
Proposal_Team_Calc__c [] ptclean = [Select Id from Proposal_Team_Calc__c where Proposal_Team__r.Funding_Record_Name__c IN :optysforupdate AND Key__c NOT IN :recordsforcleanup];
delete ptclean;

} //end method

} //end class