src/objects/Question_Choice__c.object
<CustomObject>
    <fields>
        <fullName>CT_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>Unique Id for Choice - Question Id + Points</inlineHelpText>
        <label>CT Id</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Option_Text__c</fullName>
        <label>Option Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Questions</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Question Choices</relationshipLabel>
        <relationshipName>Question_Choices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Question Choice</label>
    <nameField>
        <label>Question Choices Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Choices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questions__c.object
<CustomObject>
    <description>QuestionsObject</description>
    <fields>
        <fullName>CT_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>CT Id</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Capacity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Constituency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conservation</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Questions</label>
    <nameField>
        <label>Qs ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/QuestionParser_CT.cls
public class QuestionParser_CT extends MongoDBParser_CT {

public Questions_CT ctQuestions {get;set;}
public List<Questions__c> soQuestions;
public List<Question_Choice__c> soQuestionChoices;
    
public override void parseData() {

try {


ctQuestions = Questions_CT.parse(sJson);
soQuestions = new List<Questions__c>();
soQuestionChoices = new List<Question_Choice__c>(); 

for (Questions_CT.Rows ro: ctQuestions.rows) {
    Questions__c q = new Questions__c();
        q.Name = ro.Name;
        if (ro.question.length() > 255) {
            q.Question_Text__c = ro.question.substring(0,255);
        }
        else {
            q.Question_Text__c = ro.question;
        }
        
        q.CT_Id__c = ro.sid.xoid;
        q.Type__c = ro.section;

        soQuestions.add(q);

 if (ro.choices != NULL) {
        for (Integer i = 0; i <  ro.choices.size(); i++) {
         
            Questions_CT.Choices qc = ro.choices[i];
         
            Questions__c qp = new Questions__c();
            qp.ct_id__c = ro.sid.xoid;
            Question_Choice__c qctemp = new Question_Choice__c();
            qctemp.Questions__r = qp;
            qctemp.Points__c = qc.points;
            qctemp.Order__c = i;
            qctemp.ct_id__c =  qp.ct_id__c + ':' + qctemp.Order__c;
       
            if (qc.choice != NULL) {
                String sChoice = qc.choice;
                if (qc.choice.length() > 255) {
                    sChoice = sChoice.substring(0,255);
                }
            qctemp.Option_Text__c = sChoice;
            }
            soQuestionChoices.add(qctemp);
        }
}


}
        

}

Catch (Exception Ex) {
    system.debug('Questions Exception' + Ex);
}

}

public override void UpdateRecords() {    
    
Database.UpsertResult [] sr = Database.upsert(soQuestions, Schema.Questions__c.CT_Id__c, false);
Database.UpsertResult [] sr2 = Database.upsert(soQuestionChoices, Schema.Question_Choice__c.CT_Id__c, false);

isuccess = 0;

for (database.upsertresult sro: sr) {
    if (sro.issuccess() ) {
        isuccess ++;
    }
    else {
        system.debug(sro);
    }

  }
    
for (database.upsertresult sro: sr2) {
    if (sro.issuccess() ) {
        isuccess ++;
    }
    else {
        system.debug(sro);
    }

}
      
}
    
}