src/objects/Question_Choice__c.object
<CustomObject>
    <fields>
        <fullName>Option_Text__c</fullName>
        <label>Option Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Points</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <label>Questions</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Question Choices</relationshipLabel>
        <relationshipName>Question_Choices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Question Choice</label>
    <nameField>
        <label>Question Choices Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Choices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Questions__c.object
<CustomObject>
    <description>QuestionsObject</description>
    <fields>
        <fullName>Answer_Type__c</fullName>
        <label>Answer Type</label>
        <picklist>
            <picklistValues>
                <fullName>radio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>checkbox</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <label>Question Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Questions</label>
    <nameField>
        <label>Qs ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RARE_Campaign__c.object
<CustomObject>
    <label>Rare Campaign</label>
    <nameField>
        <label>Rare Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rare Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scorecard__c.object
<CustomObject>
    <description>This is the ScorecardObject</description>
    <fields>
        <fullName>Approver_s_Comments__c</fullName>
        <inlineHelpText>Comments entered by Approver - mostly required when rejecting a scorecard as this will be sent to submitters</inlineHelpText>
        <label>Approver&apos;s Comments</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>3000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RARE_Campaign__c</fullName>
        <label>RARE Campaign</label>
        <referenceTo>RARE_Campaign__c</referenceTo>
        <relationshipLabel>Scorecards</relationshipLabel>
        <relationshipName>Score_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Submission_Date__c</fullName>
        <label>Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Submission_Status__c</fullName>
        <description>Set by Submission Process</description>
        <inlineHelpText>Set by Submission Process</inlineHelpText>
        <label>Submission Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Send Submission Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submission Email Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Scorecard</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Score Card ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Scorecard_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Display_Order__c</fullName>
        <defaultValue>99</defaultValue>
        <inlineHelpText>Display Order on Scorecard Page</inlineHelpText>
        <label>Display Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Question_Text__c</fullName>
        <formula>Questions__r.Question_Text__c</formula>
        <label>Question Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Questions</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Scorecard Answers</relationshipLabel>
        <relationshipName>Scorecard_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RARE_Campaign__c</fullName>
        <formula>Scorecard__r.RARE_Campaign__r.Name</formula>
        <label>RARE Campaign</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scorecard__c</fullName>
        <label>Scorecard</label>
        <referenceTo>Scorecard__c</referenceTo>
        <relationshipLabel>Scorecard Answers</relationshipLabel>
        <relationshipName>Scorecard_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Select_QC_Ids__c</fullName>
        <label>Select QC Ids</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Scorecard Answer</label>
    <nameField>
        <displayFormat>SCA-{000000}</displayFormat>
        <label>Scorecard Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Scorecard_Submission__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Submitter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approver</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Scorecard__c</fullName>
        <label>Scorecard</label>
        <referenceTo>Scorecard__c</referenceTo>
        <relationshipLabel>Scorecard Submissions</relationshipLabel>
        <relationshipName>Scorecard_Submissions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Scorecard Submission</label>
    <nameField>
        <displayFormat>SUBMS-{0000}</displayFormat>
        <label>Scorecard Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard Submissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScorecardAnswerController.cls
public class ScorecardAnswerController {
    public transient List<ScorecardAnswerWrapper> SAW {get;set;}
    public transient Scorecard__c score {get;set;}
    public String scid {get;set;}
    public String teamid {get;set;}
    private Scorecard_Submission__c user;
    public String sNewValues {get;set;}
    public Boolean bShowSubmit {get;set;} 
    public Boolean bShowApprove {get;set;} 
        
    public ScorecardAnswerController() {
    //Look for scorecard Id
     if (ApexPages.currentPage().getParameters().get('scid') != NULL) {
         scid = ApexPages.currentPage().getParameters().get('scid');
         setupWrapper();
         sNewValues = '';
         bShowSubmit = TRUE;
         //Default Approve to False
         bShowApprove = FALSE;
     }
     //Look for Team Role for this scorecard as stored in Scorecard Submission Object
     if (ApexPages.currentPage().getParameters().get('trid') != NULL) {
            setupRoles(ApexPages.currentPage().getParameters().get('trid'));
     }
    }
    
    private void setupRoles(String trid) {
    List<Scorecard_Submission__c> subs = [Select Id, Role__c FROM Scorecard_Submission__c WHERE Id = :trid];
        if (subs.isEmpty() == FALSE) {
            teamid = subs[0].Id;
            if (subs[0].Role__c == 'Approver') {
                bShowSubmit = FALSE;
                bShowApprove = TRUE;    
            }
        }
    } 
        
        private void setupWrapper() {
            SAW = new List<ScorecardAnswerWrapper> ();
            Map<Id, Questions__c> qmap = new Map<Id, Questions__c> ( [Select Id, Name, Question_Text__c, Answer_Type__c, (Select Order__c, Points__c, Option_Text__c FROM Question_Choices__r Order by Order__c ASC) 
                                                                        FROM Questions__c WHERE RecordTypeId = '012800000007kFC']);
            List<Scorecard__c> scorecards = [Select Id, Name, Comment__c, Approver_s_Comments__c , score__c, Grade__c, RARE_Campaign__r.Name, 
                                        (Select Id, Questions__c, Select_QC_Ids__c from Scorecard_Answers__r Order BY Display_Order__c ASC)
                                        FROM Scorecard__c WHERE Id = :scid];    
            if (scorecards.size() > 0) {
                score = scorecards[0];
            
                for (Scorecard_Answer__c sa: score.Scorecard_Answers__r) {
                    ScorecardAnswerWrapper sawtemp = new ScorecardAnswerWrapper(sa);
                    
                    sawtemp.question = qmap.get(sa.Questions__c);
                    sawtemp.qchoices = qmap.get(sa.Questions__c).Question_Choices__r;
                    system.debug(qmap.get(sa.Questions__c)); 
                    SAW.add(sawtemp);
                }  
            }   
        }
            
        
    public class ScorecardAnswerWrapper {
        public String scorecardId {get;set;}
        public Scorecard_Answer__c sca {get;set;}
        public String selectedchoices {get;set;}
        public Questions__c question {get;set;}
        public List<Question_Choice__c> qchoices {get;set;}
    
        public ScorecardAnswerWrapper (Scorecard_Answer__c scaparam ) {
            selectedchoices = '';
            sca = scaparam;
            if (!String.IsEmpty(sca.Select_QC_Ids__c ) ) {
                selectedchoices = sca.Select_QC_Ids__c;
            }
            
        }
    }
    
    public pagereference ReceiveUpdates() {
        system.debug(sNewValues);
        return null;
    }    
    
    @RemoteAction
    public static Void ReceiveUpdates(String sNewValues, String sType, List<String> sScorecard) {
        
        system.debug(sScorecard);
        String scid = sScorecard[0];
        Scorecard__c score = new ScoreCard__c (Id = scid);
        score.Grade__c = sScorecard[1];
        score.Comment__c = sScorecard[2];
        
        if (sScorecard.size() == 4) {
            score.approver_s_Comments__c = sScorecard[3];
        }
        
        if (sType == 'Submit') {
            score.Submission_Date__c = system.today();
            score.Submission_Status__c = 'Submitted';
        }
        
        else if (sType == 'Approve') {
        score.Submission_Status__c = 'Approved';
        }
        
        else if (sType == 'Reject') {
        score.Submission_Status__c = 'Rejected';
        }
        
        update score;
        
        List<String> sNewValueList = sNewValues.split(',');
        List<Scorecard_Answer__c> newSCValues = new List<Scorecard_Answer__c>();
        for (String s: sNewValueList) {
            String [] sValueTemp = s.Split(':');
            
            Scorecard_Answer__c sctemp = new Scorecard_Answer__c(Id = sValueTemp[0], Select_QC_Ids__c  = NULL);
            if (sValueTemp.size() == 2) {
                sctemp.Select_QC_Ids__c  = sValueTemp[1];
            }
            newSCValues.add(sctemp);
        }
        system.debug(sNewValueList);
        update newSCValues;
        
       if (sType == 'Approve') {
           ScorecardProcessHandler.setAnswerChoices(new List<Id> {scId});
        }  
    }      
}