src/objects/Questions__c.object
<CustomObject>
    <description>QuestionsObject</description>
    <fields>
        <fullName>CT_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>CT Id</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Questions</label>
    <nameField>
        <label>Qs ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Scorecard__c.object
<CustomObject>
    <description>This is the ScorecardObject</description>
    <fields>
        <fullName>CT_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>CT Id</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Scorecard</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Score Card ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Scorecard_Answer__c.object
<CustomObject>
    <fields>
        <fullName>CT_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>CT Id</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Question_Type2__c</fullName>
        <label>Question Type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Questions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Questions</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Scorecard Answers</relationshipLabel>
        <relationshipName>Scorecard_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Scorecard__c</fullName>
        <label>Scorecard</label>
        <referenceTo>Scorecard__c</referenceTo>
        <relationshipLabel>Scorecard Answers</relationshipLabel>
        <relationshipName>Scorecard_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Selected_Choices__c</fullName>
        <label>Selected Choices</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>6</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Scorecard Answer</label>
    <nameField>
        <displayFormat>SCA-{000000}</displayFormat>
        <label>Scorecard Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScorecardAnswerParser_CT.cls
public class ScorecardAnswerParser_CT {

public String sJson {get;set;}
public ScorecardAnswers_CT ctAnswer {get;set;}
public Map<String, Object> m {get;set;}
public Integer isuccess {get;set;}
public List< Scorecard_Answer__c > soAnswers;
    
public void parseData() {

try {


ctAnswer = ScorecardAnswers_CT.parse(sJson);
soAnswers = new List< Scorecard_Answer__c >();

for (ScorecardAnswers_CT.Rows ro: ctAnswer.rows) {

    Scorecard_Answer__c qa = new Scorecard_Answer__c();
    
    Questions__c q = new Questions__c();
    Scorecard__c sc = new Scorecard__c();
    qa.CT_Id__c = ro.sid.xoid;
    
        q.CT_Id__c = ro.questionsid.xoid;
        sc.CT_Id__c = ro.scorecardsid.xoid;
        
        qa.Questions__r = q;
        qa.scorecard__r = sc; 
     
        qa.Question_Type2__c = ro.section;
        qa.Score__c = ro.score;
        if (ro.Choices != NULL) {
            system.debug(ro.Choices);
            String sChoices = String.Join(ro.Choices, ';');
            qa.Selected_Choices__c = sChoices;
        }
soAnswers.add(qa);
 
}
        

}

Catch (Exception Ex) {
    system.debug('Answers Exception' + Ex);
}

}

public void UpdateAnswers() {    
    
Database.UpsertResult [] sr = Database.upsert(soAnswers, Schema.Scorecard_Answer__c.CT_Id__c, false);
  isuccess = 0;

for (database.upsertresult sro: sr) {
    if (sro.issuccess() ) {
        isuccess ++;
    }
    else {
        system.debug(sro);
    }

  }
    
}
    
}