src/objects/Questions__c.object
<CustomObject>
    <description>QuestionsObject</description>
    <label>Questions</label>
    <nameField>
        <label>Qs ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/RARE_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>IMPLEMENTATION</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>COMPLETE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANCELLED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INCOMPLETE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTNERS WITHDREW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Rare Campaign</label>
    <nameField>
        <label>Rare Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rare Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scorecard__c.object
<CustomObject>
    <description>This is the ScorecardObject</description>
    <fields>
        <fullName>RARE_Campaign__c</fullName>
        <label>RARE Campaign</label>
        <referenceTo>RARE_Campaign__c</referenceTo>
        <relationshipLabel>Scorecards</relationshipLabel>
        <relationshipName>Score_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Scorecard</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Score Card ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Scorecard_Answer__c.object
<CustomObject>
    <fields>
        <fullName>Questions__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Questions</label>
        <referenceTo>Questions__c</referenceTo>
        <relationshipLabel>Scorecard Answers</relationshipLabel>
        <relationshipName>Scorecard_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RARE_Campaign__c</fullName>
        <formula>Scorecard__r.RARE_Campaign__r.Name</formula>
        <label>RARE Campaign</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scorecard__c</fullName>
        <label>Scorecard</label>
        <referenceTo>Scorecard__c</referenceTo>
        <relationshipLabel>Scorecard Answers</relationshipLabel>
        <relationshipName>Scorecard_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Scorecard Answer</label>
    <nameField>
        <displayFormat>SCA-{000000}</displayFormat>
        <label>Scorecard Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecard Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SetupNewScoreCardExtension.cls
public with sharing class SetupNewScoreCardExtension {
private final Rare_Campaign__c campaign;

public List<ScorecardProcessHandler.ScorecardAnswerSetup> NewScoreCardAnswers {get;set;}    
    
    public SetupNewScoreCardExtension(ApexPages.StandardController controller) {
        campaign = (Rare_Campaign__c)controller.getrecord();
        setupNewQuestions();
    }

private void setupNewQuestions() {

NewScoreCardAnswers = new List<ScorecardProcessHandler.ScorecardAnswerSetup> (); 

List<Questions__c> questions = ScorecardProcessHandler.getAllQuestions();

for (integer i=0; i < questions.size(); i++) {
    ScorecardProcessHandler.ScorecardAnswerSetup sap = new ScorecardProcessHandler.ScorecardAnswerSetup(i + 1, questions[i]);
    NewScoreCardAnswers.add(sap);
}


}

public pageReference createScorecard() {
Scorecard__c sc = new Scorecard__c(Rare_Campaign__c = campaign.Id, Status__c = 'Active');
insert sc;
List<Scorecard_Answer__c> newsa = new List<Scorecard_Answer__c> ();

for (ScorecardProcessHandler.ScorecardAnswerSetup sap: NewScoreCardAnswers) {
    if (sap.bInclude) {
        sap.sa.Scorecard__c = sc.Id;
        newsa.add(sap.sa);
    }
    
}
    
insert newsa;
    return new PageReference('/'+sc.Id);    
}

public PageReference SendScorecard() {
    ScorecardProcessHandler sph = new ScorecardProcessHandler();
    sph.GenerateNewScorecards(new List<Id>{campaign.Id});
    sph.generateSubmissionNotice();
    return new PageReference('/'+ campaign.Id);   
}

}