src/objects/RARE_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>CT_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>Mongo DB Unique Id</inlineHelpText>
        <label>CT Id</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>IMPLEMENTATION</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>COMPLETE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CANCELLED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>INCOMPLETE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PARTNERS WITHDREW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Rare Campaign</label>
    <nameField>
        <label>Rare Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rare Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Scorecard__c.object
<CustomObject>
    <description>This is the ScorecardObject</description>
    <fields>
        <fullName>CT_Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>CT Id</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grade__c</fullName>
        <label>Grade</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RARE_Campaign__c</fullName>
        <label>RARE Campaign</label>
        <referenceTo>RARE_Campaign__c</referenceTo>
        <relationshipLabel>Scorecards</relationshipLabel>
        <relationshipName>Score_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Rank</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reviewed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reviewed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submission_Date__c</fullName>
        <label>Submission Date</label>
        <type>Date</type>
    </fields>
    <label>Scorecard</label>
    <nameField>
        <displayFormat>SC-{000000}</displayFormat>
        <label>Score Card ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scorecards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ScorecardParser_CT.cls
public class ScorecardParser_CT extends MongoDBParser_CT {

public Scorecards_CT ctScorecards {get;set;}
public List<Scorecard__c> soScorecards;
    
public override void parseData() {

try {


ctScorecards = Scorecards_CT.parse(sJson);
soScorecards = new List<Scorecard__c>();

for (Scorecards_CT.Rows ro: ctScorecards.rows) {
    Scorecard__c q = new Scorecard__c();
    RARE_Campaign__c rc = new RARE_Campaign__c();
    rc.CT_Id__c = ro.campaignsid.xoid;
    q.RARE_Campaign__r = rc;
        q.CT_Id__c = ro.sid.xoid;
        q.Status__c = ro.status;
        q.Grade__c = ro.grade;
        q.Rank__c = ro.rank;
        q.Reviewed__c = ro.reviewed;
        //q.Type__c = ro.section;
        if (ro.due_date != NULL) {
            //String [] sdate = ro.due_date.xdate.split('-');
            //Date myDate = Date.newInstance(integer.valueof(sdate[0]), integer.valueof(sdate[1]), integer.valueof(sdate[2].left(2)));
            q.due_date__c =  convertctdate(ro.due_date.xdate);
            q.name__c = 'Scorecard:' + q.due_date__c.format();
            
        }
        
        if (ro.submission_date != NULL) {
            q.Submission_Date__c = convertctdate(ro.submission_date.xdate);
            }
        
soScorecards.add(q);
}
}
Catch (Exception Ex) {
    system.debug('Scorecard Exception' + Ex);
}

}

public override void UpdateRecords() {    
    
Database.UpsertResult [] sr = Database.upsert(soScorecards, Schema.Scorecard__c.CT_Id__c, false);
  isuccess = 0;

for (database.upsertresult sro: sr) {
    if (sro.issuccess() ) {
        isuccess ++;
    }
    else {
        system.debug(sro);
    }

  }
    
}

private date convertctdate(Long ctDate) {
    DateTime myDatetime = DateTime.newInstance(ctDate);
    return myDatetime.date();    
}
    
}