src/objects/Target__c.object
<CustomObject>
    <label>Target</label>
    <nameField>
        <label>Target Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Cohort_to_Date__c</fullName>
        <formula>If (

OR(Reference_Name__c = &apos;Fit Assessment&apos;,Reference_Name__c = &apos;EOI&apos;, Reference_Name__c = &apos;Evaluation&apos;), Completed__c +  Current__c +  Ended__c ,Completed__c +  Current__c

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Records currently in the stage plus records that have successfully exited the stage</inlineHelpText>
        <label>FY09 Cohort to Date</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Completed__c</fullName>
        <label>FY09 Completed</label>
        <summaryFilterItems>
            <field>Tracking_Details__c.Status__c</field>
            <operation>equals</operation>
            <value>Completed</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Tracking_Details__c.Reporting_Year__c</field>
            <operation>equals</operation>
            <value>FY 09</value>
        </summaryFilterItems>
        <summaryForeignKey>Tracking_Details__c.Tracking__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Current__c</fullName>
        <label>FY09 Current</label>
        <summaryFilterItems>
            <field>Tracking_Details__c.Status__c</field>
            <operation>equals</operation>
            <value>Current</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Tracking_Details__c.Reporting_Year__c</field>
            <operation>equals</operation>
            <value>FY 09</value>
        </summaryFilterItems>
        <summaryForeignKey>Tracking_Details__c.Tracking__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Dash_Table__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Show in Dash Table?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Display_Stage__c</fullName>
        <formula>text(Display_Order__c)  &amp;&quot; : &quot; &amp; Name</formula>
        <label>Display Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ended__c</fullName>
        <label>FY09 Ended</label>
        <summaryFilterItems>
            <field>Tracking_Details__c.Status__c</field>
            <operation>equals</operation>
            <value>Ended</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Tracking_Details__c.Reporting_Year__c</field>
            <operation>equals</operation>
            <value>FY 09</value>
        </summaryFilterItems>
        <summaryForeignKey>Tracking_Details__c.Tracking__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Target_Date__c</fullName>
        <label>Target Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Target__c</fullName>
        <label>Target</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Tracking</label>
    <nameField>
        <label>Stage</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/bfc_vftrackingdashboard.cls
public class bfc_vftrackingdashboard {

public ApexPages.StandardSetController setDash {
        get {
            if(setDash == null) {
                setDash = new ApexPages.StandardSetController(Database.getQueryLocator([Select Target__c, Cohort_to_Date__c, Target_Date__c, Ended__c, Display_Stage__c, Current__c, Completed__c From Tracking__c where Dash_Table__c = true order by Display_Stage__c  ASC]));
            }
            return setDash;
        }
        set;
    }
    public List<Tracking__c> getTracking() {
         return (List<Tracking__c>) setDash.getRecords();
    }

static testmethod void bfc_test_controller() {

PageReference pageRef = Page.trackingreport1;
Test.setCurrentPage(pageRef);  

bfc_vftrackingdashboard bfc_vftrackingdashboard = new bfc_vftrackingdashboard();
bfc_vftrackingdashboard.getTracking();
}
}